" ubuntu has an old neovim version, don't notify about it
let g:go_version_warning = 0

set runtimepath+=~/.vim_runtime
source ~/.vim/vim-runtime/autoload/pathogen.vim

source ~/.vim/vim-runtime/vimrcs/basic.vim
source ~/.vim/vim-runtime/vimrcs/filetypes.vim
source ~/.vim/vim-runtime/vimrcs/plugins_config.vim
source ~/.vim/vim-runtime/vimrcs/extended.vim

" custom settings
color monokai

" don't switch to visual mode on mouseclick
set mouse-=a

au BufNewFile,BufRead *.s,*.S set filetype=arm " arm = armv6/7
