set runtimepath+=~/.vim_runtime
source ~/.vim/vim-runtime/autoload/pathogen.vim

source ~/.vim/vim-runtime/vimrcs/basic.vim
source ~/.vim/vim-runtime/vimrcs/filetypes.vim
source ~/.vim/vim-runtime/vimrcs/plugins_config.vim
source ~/.vim/vim-runtime/vimrcs/extended.vim

" custom settings
color monokai
